#Load in the required dependencies
library(SIBER)

# Import Data -------------------------------------------------------------

#import your correspondence data
#the First column should be sites/assemblages, columns 2 and 3 are CA1 and 2 scores respectively. and column 4 should be the weighting factor
data <-read.csv(file = file.choose())

#import the convex hulldata
#this version of the data is a reconfiguration of the above. For each taxa (named in column 1) all sites/assemblages they occur in and the corresponding CA scores are provided in columns 2-4
HullData<-read.csv(file = file.choose())

#a vector of All relevant taxa in your data set in whatever order you would like them printed in output
taxa<-c("Paranthropus", "Homo", "Erectus", "NonErectus", "Aepyceros", "Beatragus", "Connochaetes", "Damaliscus", "Megalotragus", "Antidorcas",
        "Eudorcas", "Pelorovis", "Kobus", "Menelikia", "Tragelaphus", "Giraffa", "Sivatherium", "Metridiochorus", "Kolpochoeurs", "Notochorus",
        "Equus", "Eurygnathohippus", "Ceratotherium", "Lophocebus", "Parapapio", "Theropithecus", "Colobus", "Rhinocolobus", "Deinotherium", "Elephas")

# a vector of the sample size for each taxon. MUST BE CORRELATED 1 to 1 with the above vector
hsamp<-c(53, 46, 15, 14, 137, 12, 35, 69, 101, 62, 28, 105, 373, 103, 250, 133, 51, 487, 420, 133, 230, 101, 33, 48, 22, 563, 15, 28, 25, 112)

#A vector of indexes equal to the length of the data sheet.
#This allows for sites to be randomly drawn by the function below
samplevec<-seq(1:length(data[,1]))


# Internal Functions ------------------------------------------------------

#this function randomly samples all sites, with repeats, and calculates convex hull statistics for the random sample
# The only input for this function is how large you want your sample size to be.
HullSample<-function(sampsize){
  Sample <- sample(samplevec, size = sampsize, replace = TRUE, prob = data$probability) #draws random numnbers with replacement from the index vector, weighted by the probability of the "data" object 
  Reconstruct<-data[Sample,] #rebuilds a matrix using only the sampled rows
  Sca1 <- Reconstruct$ca1 #independent vector of all CA1 scores
  Sca2 <- Reconstruct$ca2 #independent vector of all CA2 scores
  SHull <- siberConvexhull(Sca1,Sca2) #calculates Siberconvex hull statistics for the sampled object
  SHull[[1]] #returns the hull area
}

#This function automates the bootstrapping process
# Inputs: HullData= the object storing your hulldata, Taxon = the taxon you would like to use as reference, replicates = how many times you want to bootstrap 
runreps<-function(HullData,taxon,replicates) {
  pull<-HullData[which(HullData$taxon == taxon), ] #selects all sites that are tied to a taxon
  pullca1<-pull$ca1 #stores the CA1 scores
  pullca2<-pull$ca2 #Stores the CA2 scores
  chull<-siberConvexhull(pullca1,pullca2) #finds the SIBER convex hull data for that taxon
  charea<-chull[[1]] #pulls hull area of that taxon
  
  hullsize<-replicate(replicates, HullSample(hsamp[which(taxa==taxon)])) #bootstrapping that randomly pulls data equal to the number of samples for the reference taxon from the full data set
  Quant<-quantile(hullsize,c(.025,.975)) #identifies the 95% confidence interval for the data
  Output<-list(hullsize, charea, Quant) #collects the output of every bootstrap, the Actual convex hull area of the taxa, and the 95% confidence interval into a storage object
  return(Output) # prints the storage object to be viewed or sent to a global object
}

#function to generate a histogram of bootstrapping analysis results for a specified taxon
# inputs: results = object storing the results lists generated by runreps, taxa= the taxa you wish to show results for
HullHist<-function(result,taxa){
  hist(Results[[taxa]][[1]], main=taxa, xlim=c(0,1), col = "#fcfdbf") #creates the base histogram, in yellow for convex hull areas that result from the bootstrap
  abline(v=Results[[taxa]][[2]], col="#de4968", lwd=5) # draws a red vertical line representing the ACTUAL/REALIZED convex hull area
  abline(v=Results[[taxa]][[3]], col="#3b0f70", lwd=2) # Draws vertical blue lines at the bounds of the 95% confidence interval
}


# Analysis ----------------------------------------------------------------

#runs bootstrapping analysis for convex hull size for every taxa in the data set
Results<-lapply(taxa, runreps, HullData=HullData, replicates=100000)
#names each object in the results list after its representative taxa
names(Results)<-taxa

#Makes a PDF file of all taxa historgram, each occupies one page, can be modified to run of a subset by using a vector of names with only selected taxa
pdf(file="Hull Histograms All.pdf") # Name the PDF 
lapply(taxa, HullHist, result=Results) #runs the histogram generator for all taxa in the named list, currently "taxa" which is the vector of all taxa

dev.off()#turns off the PDF generating options.
